name: Full Slate: Lines + Features + Model

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: nfl-prop-model
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # REQUIRED: pulls lines from The Odds API (needs repo secret ODDS_API_KEY)
      - name: Fetch sportsbook lines via The Odds API
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/fetch_lines.py --out inputs/sportsbook_lines.csv

      # Optional: previously saved priors as artifact
      - name: Download priors (if available)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: player_priors
          path: inputs/

      # Optional: feature fetch; never aborts the job if it fails
      - name: Fetch features (nflverse + NWS) (optional)
        continue-on-error: true
        run: |
          python scripts/fetch_features.py --out inputs/features.parquet || echo "Skipping features (optional)"

      - name: Run model
        run: |
          python scripts/run_model.py

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: model_outputs
          path: outputs/
