name: Full Slate: Lines + Features + Model

on:
  workflow_dispatch:
    inputs:
      refresh_lines:
        description: "Fetch sportsbook lines (requires ODDS_API_KEY secret)"
        type: boolean
        default: false
        required: false
      season:
        description: "Season (e.g. 2025); leave blank to auto-detect"
        type: string
        required: false
        default: ""
      week:
        description: "Week number (e.g. 5); leave blank to auto-detect"
        type: string
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: nfl-prop-model
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (with nfl_data_py compatibility)
        run: |
          set -e
          python -m pip install -U pip setuptools wheel
          # Try requirements.txt first (okay if you don't have one)
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || echo "requirements.txt install had conflicts; continuing..."
          fi
          # Ensure versions compatible with nfl_data_py
          pip install "pandas<2.0" "numpy<2.0" nfl_data_py==0.3.3
          # Common libs used elsewhere
          pip install requests scipy pyarrow

      - name: Prepare folders
        run: |
          mkdir -p inputs outputs

      # Optional: download previously uploaded priors (won't fail if not present)
      - name: Download priors (if available)
        uses: actions/download-artifact@v4
        with:
          name: player_priors
          path: inputs
        continue-on-error: true

      # ---------- OPTIONAL: Fetch sportsbook lines (needs ODDS_API_KEY) ----------
      - name: Fetch sportsbook lines (optional)
        if: ${{ inputs.refresh_lines == true && env.ODDS_API_KEY != '' }}
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          set -e
          echo "Fetching sportsbook lines with provided API key..."
          # This expects scripts/fetch_lines.py in the repo
          # and writes to inputs/sportsbook_lines.csv
          python scripts/fetch_lines.py --out inputs/sportsbook_lines.csv || {
            echo "::warning::Fetch lines failed (422 or API issue). Continuing without fresh lines."
          }
          ls -lh inputs || true

      # ---------- REQUIRED: Fetch features with explicit --out ----------
      - name: Fetch features (nflverse + NWS)
        env:
          SEASON: ${{ inputs.season }}
          WEEK:   ${{ inputs.week }}
        run: |
          set -e
          # scripts/fetch_features.py must exist in your repo.
          # It requires --out; season/week are optional and only passed when non-empty.
          python scripts/fetch_features.py \
            --out inputs/features.csv \
            ${SEASON:+--season "$SEASON"} \
            ${WEEK:+--week "$WEEK"}

          echo "Wrote features to inputs/features.csv"
          head -n 5 inputs/features.csv || true

      # ---------- Run your model ----------
      - name: Run model
        run: |
          set -e
          # Make sure your run_model.py reads inputs/features.csv and (optionally)
          # inputs/sportsbook_lines.csv, then writes results to outputs/
          python run_model.py
          echo "Model finished. Outputs:"
          ls -lh outputs || true

      # ---------- Upload artifacts ----------
      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs
          if-no-files-found: warn

      - name: Upload inputs used (for traceability)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inputs
          path: |
            inputs/features.csv
            inputs/sportsbook_lines.csv
          if-no-files-found: warn
