# .github/workflows/fetch_and_run.yml
name: "Full Slate: Lines + Features + Model (defensive bootstrap)"

on:
  workflow_dispatch:
    inputs:
      refresh_lines:
        description: "Pull sportsbook lines via Odds API (requires ODDS_API_KEY secret)"
        type: boolean
        required: false
        default: false
      season:
        description: "Season (e.g., 2025). Leave blank to auto-detect"
        required: false
        default: ""
      weeks:
        description: "Comma-separated weeks (e.g., 1,2,3). Leave blank to auto-detect"
        required: false
        default: ""
  push:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: nfl-prop-model
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      # Optional: only runs if you checked 'refresh_lines' or if the secret is present.
      - name: "Fetch sportsbook lines (optional)"
        if: ${{ inputs.refresh_lines == true || env.ODDS_API_KEY != '' }}
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python - <<'PY'
          import os, subprocess, shlex
          key = os.environ.get("ODDS_API_KEY", "")
          if not key:
              print("No ODDS_API_KEY secret; skipping sportsbook pulls.")
              raise SystemExit(0)
          season = "${{ inputs.season }}".strip()
          weeks  = "${{ inputs.weeks }}".strip()
          cmd = ["python","scripts/fetch_lines.py","--out","inputs/sportsbook_lines.csv"]
          if season: cmd += ["--season", season]
          if weeks:  cmd += ["--weeks",  weeks]
          print("Running:", " ".join(shlex.quote(c) for c in cmd))
          subprocess.check_call(cmd)
          PY

      - name: "Fetch features (nflverse + NWS)"
        run: |
          set -e
          F=fetch_features.py
          if [ -f scripts/fetch_features.py ]; then F=scripts/fetch_features.py; fi
          # These args are placeholders; the script can ignore blanks
          python "$F" \
            --game_id "" \
            --home_team "" \
            --away_team "" \
            --lat "" \
            --lon ""

      - name: "Run model"
        run: python run_model.py

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: model_outputs
          path: |
            outputs/**
            inputs/sportsbook_lines.csv
          if-no-files-found: warn
