name: Full Slate: Lines + Features + Model (defensive bootstrap)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: nfl-prop-model
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # If you add this in repo Settings ▸ Secrets and variables ▸ Actions
      # the workflow will pick it up automatically
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure standard folders
        run: |
          set -euxo pipefail
          mkdir -p inputs outputs scripts .github/workflows
          # Keep folders in git
          touch inputs/.gitkeep outputs/.gitkeep

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Fallback (shouldn't hit, but keeps run green)
            pip install numpy==1.26.4 pandas==2.1.4 pyarrow==15.0.2 requests==2.32.3
          fi

      - name: Show environment
        run: |
          python -V
          pip --version
          pip freeze | sort | sed -n '1,120p'

      # --- Sanity: never fail the build below this line ---
      - name: Sanity – make sure Python can import pandas/numpy
        run: |
          python - <<'PY'
          import sys, numpy as np, pandas as pd
          print("NumPy:", np.__version__)
          print("pandas:", pd.__version__)
          print("Python:", sys.version)
          PY

      # Make these scripts optional. If missing, we just log and move on.
      - name: Run advanced.py (optional)
        continue-on-error: true
        run: |
          set -euxo pipefail
          if [ -f scripts/advanced.py ]; then
            python scripts/advanced.py --dry-run
          else
            echo "scripts/advanced.py not found (ok while bootstrapping)."
          fi

      - name: Run fetch_features.py (optional)
        continue-on-error: true
        run: |
          set -euxo pipefail
          if [ -f scripts/fetch_features.py ]; then
            python scripts/fetch_features.py || true
          else
            echo "scripts/fetch_features.py not found (ok while bootstrapping)."
          fi

      - name: Run engine.py (optional)
        continue-on-error: true
        run: |
          set -euxo pipefail
          if [ -f scripts/engine.py ]; then
            python scripts/engine.py || true
          else
            echo "scripts/engine.py not found (ok while bootstrapping)."
          fi

      - name: Upload outputs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: model-outputs
          path: outputs/
          if-no-files-found: ignore
